export const events = [
  {
    id: "1",
    name: "Youth Music Festival",
    description:
      "Join us for an exciting day of live music performances by emerging youth bands and artists.",
    imageUrl: "https://picsum.photos/200?random=1",
    startDateTime: "2025-04-15T12:00:00",
    endDateTime: "2025-04-15T18:00:00",
    location: "Central Park, New York",
    organizer: "Youth Culture Collective",
  },
  {
    id: "2",
    name: "Dance Battle Championship",
    description:
      "Come and cheer for the best dancers as they battle it out for the title of the best youth dancer.",
    imageUrl: "https://picsum.photos/200?random=2",
    startDateTime: "2025-05-10T14:00:00",
    endDateTime: "2025-05-10T20:00:00",
    location: "Los Angeles Youth Arena",
    organizer: "Urban Moves",
  },
  {
    id: "3",
    name: "Street Art Showcase",
    description:
      "A festival of creativity featuring live street art installations by talented young artists.",
    imageUrl: "https://picsum.photos/200?random=3",
    startDateTime: "2025-06-05T10:00:00",
    endDateTime: "2025-06-05T16:00:00",
    location: "Downtown, Chicago",
    organizer: "Creative Youth Society",
  },
  {
    id: "4",
    name: "Skateboard Showdown",
    description:
      "Watch the best young skateboarders show off their skills in a high-energy competition.",
    imageUrl: "https://picsum.photos/200?random=4",
    startDateTime: "2025-07-01T12:00:00",
    endDateTime: "2025-07-01T17:00:00",
    location: "Venice Beach, California",
    organizer: "Skate Crew",
  },
  {
    id: "5",
    name: "Youth Film Screening",
    description:
      "A screening of short films created by young filmmakers showcasing their stories and visions.",
    imageUrl: "https://picsum.photos/200?random=5",
    startDateTime: "2025-08-10T18:00:00",
    endDateTime: "2025-08-10T21:00:00",
    location: "San Francisco Film Hub",
    organizer: "Young Creators Network",
  },
  {
    id: "6",
    name: "Poetry Slam Night",
    description:
      "An open mic night where young poets share their words and compete for the title of best poet.",
    imageUrl: "https://picsum.photos/200?random=6",
    startDateTime: "2025-09-12T19:00:00",
    endDateTime: "2025-09-12T22:00:00",
    location: "Brooklyn Youth Center",
    organizer: "Youth Voices",
  },
  {
    id: "7",
    name: "Youth Talent Show",
    description:
      "A stage for young performers to showcase their unique talents—whether it's singing, dancing, or magic.",
    imageUrl: "https://picsum.photos/200?random=7",
    startDateTime: "2025-09-25T18:00:00",
    endDateTime: "2025-09-25T21:00:00",
    location: "Miami Youth Auditorium",
    organizer: "Future Stars Productions",
  },
  {
    id: "8",
    name: "Youth Fashion Show",
    description:
      "A celebration of youthful fashion where young designers and models showcase their latest trends.",
    imageUrl: "https://picsum.photos/200?random=8",
    startDateTime: "2025-10-12T16:00:00",
    endDateTime: "2025-10-12T19:00:00",
    location: "Los Angeles Fashion District",
    organizer: "Teen Couture",
  },
  {
    id: "9",
    name: "Extreme Sports Festival",
    description:
      "An adrenaline-pumping event featuring youth athletes competing in BMX, parkour, and more.",
    imageUrl: "https://picsum.photos/200?random=9",
    startDateTime: "2025-11-01T10:00:00",
    endDateTime: "2025-11-01T18:00:00",
    location: "Austin, TX",
    organizer: "Xtreme Youth Sports",
  },
  {
    id: "10",
    name: "Youth Tech Expo",
    description:
      "Explore cutting-edge tech innovations created by young minds, from robotics to app development.",
    imageUrl: "https://picsum.photos/200?random=10",
    startDateTime: "2025-11-20T09:00:00",
    endDateTime: "2025-11-20T17:00:00",
    location: "Seattle, WA",
    organizer: "Future Innovators",
  },
  {
    id: "11",
    name: "Youth Gaming Tournament",
    description:
      "Compete in an exciting gaming tournament, where youth players face off in popular video games.",
    imageUrl: "https://picsum.photos/200?random=11",
    startDateTime: "2025-12-03T12:00:00",
    endDateTime: "2025-12-03T18:00:00",
    location: "San Diego, CA",
    organizer: "Gaming League",
  },
  {
    id: "12",
    name: "Youth Open Mic Night",
    description:
      "A chance for young musicians, poets, and performers to share their talents with a supportive audience.",
    imageUrl: "https://picsum.photos/200?random=12",
    startDateTime: "2025-12-15T19:00:00",
    endDateTime: "2025-12-15T22:00:00",
    location: "Chicago, IL",
    organizer: "Teen Arts Collective",
  },
  {
    id: "13",
    name: "Youth Photography Contest",
    description:
      "Submit your best photo and compete for a chance to win exciting prizes and recognition.",
    imageUrl: "https://picsum.photos/200?random=13",
    startDateTime: "2025-12-18T10:00:00",
    endDateTime: "2025-12-18T16:00:00",
    location: "Washington, D.C.",
    organizer: "Young Photographers Guild",
  },
  {
    id: "14",
    name: "Youth Theatre Production",
    description:
      "Enjoy a youth-led theatrical production, showcasing the creativity and talent of young actors.",
    imageUrl: "https://picsum.photos/200?random=14",
    startDateTime: "2025-12-20T19:00:00",
    endDateTime: "2025-12-20T22:00:00",
    location: "Atlanta, GA",
    organizer: "Youth Theatre Alliance",
  },
  {
    id: "15",
    name: "Youth Adventure Camp",
    description:
      "Join us for an adventurous camp experience full of outdoor activities like hiking, rafting, and team-building games.",
    imageUrl: "https://picsum.photos/200?random=15",
    startDateTime: "2025-12-27T08:00:00",
    endDateTime: "2025-12-27T17:00:00",
    location: "Sedona, AZ",
    organizer: "Youth Outdoors",
  },
];
