import type { Metadata } from "next";
import { Montserrat, Open_Sans } from "next/font/google";
import "./globals.css";
import SWRProvider from "../providers/swr-provider";
import Header from "@/layout/Header";
import Footer from "@/layout/Footer";
import Loader from "@/components/Loader";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tapakila",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${montserrat.variable} antialiased`}
      >
        <Header />
        <SWRProvider>
          <Loader />
          <div className="mt-20 md:mt-26 w-full max-w-full">
            <NuqsAdapter>{children}</NuqsAdapter>
          </div>
        </SWRProvider>
        <Footer />
      </body>
    </html>
  );
}
