import type { Metadata } from "next";
import { Montserrat, Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/layout/Header";
import Footer from "@/layout/Footer";
import { SWRConfig } from "swr";
import { fetcher } from "@/lib/fetcher";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tapakila",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${montserrat.variable} antialiased`}
      >
        <Header />
        <SWRConfig
          value={{
            fetcher: fetcher,
          }}
        >
          <div className="mt-20 md:mt-26 w-full max-w-full">{children}</div>
        </SWRConfig>
        <Footer />
      </body>
    </html>
  );
}
